name: Artifacts (Simple)

on: 
  workflow_dispatch:
    inputs:
      jobToFail:
        type: choice
        description: What job should fail
        required: true
        default: deploy-production
        options: 
        - job_1
        - job_2
        - none

jobs:
  job_1:
    name: Add Artifact
    runs-on: self-hosted
    steps:
      - run: |
          NOW=$(date)
          echo "NOW: $NOW" > now.txt
      - name: Upload now.txt
        uses: actions/upload-artifact@v2
        with:
          name: now
          path: now.txt
      - if: ${{ github.event.inputs.jobToFail == 'job_1' && github.run_attempt == '1' }}
        run: exit 1

  job_2:
    name: Display results
    needs: job_1
    runs-on: self-hosted
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v4.1.7
        with:
          name: now
          path: ~/downloads/now
      - run: |
          NOW=$(date)
          echo "NOW: $NOW"
      - name: Print the final result
        shell: bash
        run: |
          value=`cat ~/downloads/now/now.txt`
          echo The result is $value
      - if: ${{ github.event.inputs.jobToFail == 'job_2' && github.run_attempt == '1' }}
        run: exit 1
